@isTest
public class gdfsuezComBefChpCommunV2New_Test {
	static testMethod void testV2() {
	gdfsuezComBefChpCommunV2New v2 = new gdfsuezComBefChpCommunV2New();
	new gdfsuezComBefChpCommunV2New.intervalleMontant_element();
	new gdfsuezComBefChpCommunV2New.canalDt();
	new gdfsuezComBefChpCommunV2New.system_element();
	new gdfsuezComBefChpCommunV2New.messageRetour_element();
	new gdfsuezComBefChpCommunV2New.typologieFRDt();
	new gdfsuezComBefChpCommunV2New.intervalleMontantDt();
	new gdfsuezComBefChpCommunV2New.detail_element();
	new gdfsuezComBefChpCommunV2New.serviceSouscritDt();
	new gdfsuezComBefChpCommunV2New.Dates_element();
	new gdfsuezComBefChpCommunV2New.monetaireDt();
	new gdfsuezComBefChpCommunV2New.intervalledDt();
	new gdfsuezComBefChpCommunV2New.blocageDt();
	new gdfsuezComBefChpCommunV2New.messageRetoursDt();
	new gdfsuezComBefChpCommunV2New.date_element();
	new gdfsuezComBefChpCommunV2New.contratDt();
	new gdfsuezComBefChpCommunV2New.actionMajDt();
	new gdfsuezComBefChpCommunV2New.refPersonneDt();
	new gdfsuezComBefChpCommunV2New.logDt();
	new gdfsuezComBefChpCommunV2New.adresseDt();
	new gdfsuezComBefChpCommunV2New.listeDatesDt();
	new gdfsuezComBefChpCommunV2New.system_path_element();
	new gdfsuezComBefChpCommunV2New.listeValeursDt();
	new gdfsuezComBefChpCommunV2New.contextDt();
}
}