/**
 * @File Name          : HP_HappeHeader_TEST.cls
 * @Description        : TO BE REMOVED
 * @Author             : Mohamed Aamer
 * @Group              : 
 * @Last Modified By   : Vincent Albiser
 * @Last Modified On   : 04/06/2020 à 11:25:00
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    13/02/2020   Mohamed Aamer     Initial Version
**/
@IsTest
public with sharing class HP_HappeHeader_TEST {


}