/**
 * @File Name          : HP_WRP032_APIHourConsentementsQuestions.cls
 * @Description        : 
 * @Author             : Mouhamadoune Coulibaly
 * @Group              : 
 * @Last Modified By   : Mouhamadoune Coulibaly
 * @Last Modified On   : 10/03/2020 à 14:46:47
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    20/02/2020   Mouhamadoune Coulibaly     Initial Version
**/
public with sharing class HP_WRP032_APIHourConsentementsQuestions {
	@AuraEnabled
    public String id;
	@AuraEnabled
    public String idQuestionnaire;
	@AuraEnabled
	public String idQuestion;
	@AuraEnabled
	public String codeQuestionnaireQuestion;
	@AuraEnabled
	public String libelleQuestion;
	@AuraEnabled
	public String detailQuestion;
    
    
}