/*
*@Auhtor: Paul Ghoussoub
*@Description: Classe de test de VI_gdfsuezComBefChpCalypsoGestionprele
*@CreatedDate: 9/12/2021
*/
@isTest
public class VI_gdfsuezComBefChpCalypsoGestion_Test {
    @isTest
    static void testMethod1(){
        VI_gdfsuezComBefChpCalypsoGestionprele.demanderPrelevementResponse_element demanderPrelevementResponse_element =new VI_gdfsuezComBefChpCalypsoGestionprele.demanderPrelevementResponse_element();
        VI_gdfsuezComBefChpCalypsoGestionprele.listeCompteClientDt listeCompteClientDt =new VI_gdfsuezComBefChpCalypsoGestionprele.listeCompteClientDt();
        VI_gdfsuezComBefChpCalypsoGestionprele.demanderPrelevementOutputDt demanderPrelevementOutputDt =new VI_gdfsuezComBefChpCalypsoGestionprele.demanderPrelevementOutputDt();
        VI_gdfsuezComBefChpCalypsoGestionprele.modifierCoordonneeBancaire_element modifierCoordonneeBancaire_element =new VI_gdfsuezComBefChpCalypsoGestionprele.modifierCoordonneeBancaire_element();
        VI_gdfsuezComBefChpCalypsoGestionprele.demanderPrelevement_element demanderPrelevement_element =new VI_gdfsuezComBefChpCalypsoGestionprele.demanderPrelevement_element();
        VI_gdfsuezComBefChpCalypsoGestionprele.listePersonneDt listePersonneDt =new VI_gdfsuezComBefChpCalypsoGestionprele.listePersonneDt();
        VI_gdfsuezComBefChpCalypsoGestionprele.mandatDt mandatDt =new VI_gdfsuezComBefChpCalypsoGestionprele.mandatDt();        
        VI_gdfsuezComBefChpCalypsoGestionprele.modifierCoordonneeBancaireInputDt modifierCoordonneeBancaireInputDt =new VI_gdfsuezComBefChpCalypsoGestionprele.modifierCoordonneeBancaireInputDt();
        VI_gdfsuezComBefChpCalypsoGestionprele.modifierCoordonneeBancaireResponse_element modifierCoordonneeBancaireResponse_element =new VI_gdfsuezComBefChpCalypsoGestionprele.modifierCoordonneeBancaireResponse_element();
        VI_gdfsuezComBefChpCalypsoGestionprele.mandatDPDt mandatDPDt =new VI_gdfsuezComBefChpCalypsoGestionprele.mandatDPDt();
        VI_gdfsuezComBefChpCalypsoGestionprele.listeServicesGestionDt listeServicesGestionDt =new VI_gdfsuezComBefChpCalypsoGestionprele.listeServicesGestionDt();
        VI_gdfsuezComBefChpCalypsoGestionprele.compteClientDt compteClientDt =new VI_gdfsuezComBefChpCalypsoGestionprele.compteClientDt();
        VI_gdfsuezComBefChpCalypsoGestionprele.coordonneeBancaireDt coordonneeBancaireDt =new VI_gdfsuezComBefChpCalypsoGestionprele.coordonneeBancaireDt();
        VI_gdfsuezComBefChpCalypsoGestionprele.demanderPrelevementInputDt demanderPrelevementInputDt =new VI_gdfsuezComBefChpCalypsoGestionprele.demanderPrelevementInputDt();
        VI_gdfsuezComBefChpCalypsoGestionprele.modifierCoordonneeBancaireOutputDt modifierCoordonneeBancaireOutputDt =new VI_gdfsuezComBefChpCalypsoGestionprele.modifierCoordonneeBancaireOutputDt();
        VI_gdfsuezComBefChpCalypsoGestionprele.GestionPrelevementPort GestionPrelevementPort =new VI_gdfsuezComBefChpCalypsoGestionprele.GestionPrelevementPort();
    }
}