@isTest
public class VI_gdfsuezBefCalypsoMandatV1_Test {
	@isTest
    static void testMethod1(){
        VI_gdfsuezBefCalypsoMandatV1.listeMandatsDt listeMandatsDt=new VI_gdfsuezBefCalypsoMandatV1.listeMandatsDt();
        VI_gdfsuezBefCalypsoMandatV1.demanderSignatureInputDt demanderSignatureInputDt=new VI_gdfsuezBefCalypsoMandatV1.demanderSignatureInputDt();
        VI_gdfsuezBefCalypsoMandatV1.lireMandat_element lireMandat_element=new VI_gdfsuezBefCalypsoMandatV1.lireMandat_element();
        VI_gdfsuezBefCalypsoMandatV1.personne_element personne_element=new VI_gdfsuezBefCalypsoMandatV1.personne_element();
        VI_gdfsuezBefCalypsoMandatV1.canalCodeDt canalCodeDt=new VI_gdfsuezBefCalypsoMandatV1.canalCodeDt();
        VI_gdfsuezBefCalypsoMandatV1.SignerMandatOutputDt SignerMandatOutputDt=new VI_gdfsuezBefCalypsoMandatV1.SignerMandatOutputDt();
        VI_gdfsuezBefCalypsoMandatV1.confirmerSignature_element confirmerSignature_element=new VI_gdfsuezBefCalypsoMandatV1.confirmerSignature_element();
        VI_gdfsuezBefCalypsoMandatV1.confirmerSignatureInputDt confirmerSignatureInputDt=new VI_gdfsuezBefCalypsoMandatV1.confirmerSignatureInputDt();
        VI_gdfsuezBefCalypsoMandatV1.signerMandat_element signerMandat_element=new VI_gdfsuezBefCalypsoMandatV1.signerMandat_element();
        VI_gdfsuezBefCalypsoMandatV1.demanderSignatureResponse_element demanderSignatureResponse_element=new VI_gdfsuezBefCalypsoMandatV1.demanderSignatureResponse_element();
        VI_gdfsuezBefCalypsoMandatV1.composerMandatResponse_element composerMandatResponse_element=new VI_gdfsuezBefCalypsoMandatV1.composerMandatResponse_element();
        VI_gdfsuezBefCalypsoMandatV1.creerMandatResponse_element creerMandatResponse_element=new VI_gdfsuezBefCalypsoMandatV1.creerMandatResponse_element();
        VI_gdfsuezBefCalypsoMandatV1.majMandatOutputDt majMandatOutputDt=new VI_gdfsuezBefCalypsoMandatV1.majMandatOutputDt();
        VI_gdfsuezBefCalypsoMandatV1.SignerMandatInputDt SignerMandatInputDt=new VI_gdfsuezBefCalypsoMandatV1.SignerMandatInputDt();
        VI_gdfsuezBefCalypsoMandatV1.mandatCompose_element mandatCompose_element=new VI_gdfsuezBefCalypsoMandatV1.mandatCompose_element();
        VI_gdfsuezBefCalypsoMandatV1.majMandatResponse_element majMandatResponse_element=new VI_gdfsuezBefCalypsoMandatV1.majMandatResponse_element();
        VI_gdfsuezBefCalypsoMandatV1.listeCompteClientDT listeCompteClientDT=new VI_gdfsuezBefCalypsoMandatV1.listeCompteClientDT();
        VI_gdfsuezBefCalypsoMandatV1.confirmerSignatureResponse_element confirmerSignatureResponse_element=new VI_gdfsuezBefCalypsoMandatV1.confirmerSignatureResponse_element();
        VI_gdfsuezBefCalypsoMandatV1.rechercherMandat_element rechercherMandat_element=new VI_gdfsuezBefCalypsoMandatV1.rechercherMandat_element();
        VI_gdfsuezBefCalypsoMandatV1.listePersonnetDt listePersonnetDt=new VI_gdfsuezBefCalypsoMandatV1.listePersonnetDt();
        VI_gdfsuezBefCalypsoMandatV1.composerMandat_element composerMandat_element=new VI_gdfsuezBefCalypsoMandatV1.composerMandat_element();
        VI_gdfsuezBefCalypsoMandatV1.composerMandatInputDt composerMandatInputDt=new VI_gdfsuezBefCalypsoMandatV1.composerMandatInputDt();
        VI_gdfsuezBefCalypsoMandatV1.lireMandatResponse_element lireMandatResponse_element=new VI_gdfsuezBefCalypsoMandatV1.lireMandatResponse_element();
        VI_gdfsuezBefCalypsoMandatV1.creerMandatInputDt creerMandatInputDt=new VI_gdfsuezBefCalypsoMandatV1.creerMandatInputDt();
        VI_gdfsuezBefCalypsoMandatV1.rechercherMandatResponse_element rechercherMandatResponse_element=new VI_gdfsuezBefCalypsoMandatV1.rechercherMandatResponse_element();
        VI_gdfsuezBefCalypsoMandatV1.mandatDt mandatDt=new VI_gdfsuezBefCalypsoMandatV1.mandatDt();
        VI_gdfsuezBefCalypsoMandatV1.signerMandatResponse_element signerMandatResponse_element=new VI_gdfsuezBefCalypsoMandatV1.signerMandatResponse_element();
        VI_gdfsuezBefCalypsoMandatV1.rechercherMandatOutputDt rechercherMandatOutputDt=new VI_gdfsuezBefCalypsoMandatV1.rechercherMandatOutputDt();
        VI_gdfsuezBefCalypsoMandatV1.demanderSignature_element demanderSignature_element=new VI_gdfsuezBefCalypsoMandatV1.demanderSignature_element();
        VI_gdfsuezBefCalypsoMandatV1.compteClientConfirmerDt compteClientConfirmerDt=new VI_gdfsuezBefCalypsoMandatV1.compteClientConfirmerDt();
        VI_gdfsuezBefCalypsoMandatV1.majMandat_element majMandat_element=new VI_gdfsuezBefCalypsoMandatV1.majMandat_element();
        VI_gdfsuezBefCalypsoMandatV1.rechercherMandatInputDt rechercherMandatInputDt=new VI_gdfsuezBefCalypsoMandatV1.rechercherMandatInputDt();
        VI_gdfsuezBefCalypsoMandatV1.listeCompteClient_element listeCompteClient_element=new VI_gdfsuezBefCalypsoMandatV1.listeCompteClient_element();
        VI_gdfsuezBefCalypsoMandatV1.creerMandat_element creerMandat_element=new VI_gdfsuezBefCalypsoMandatV1.creerMandat_element();
        VI_gdfsuezBefCalypsoMandatV1.majMandatInputDt majMandatInputDt=new VI_gdfsuezBefCalypsoMandatV1.majMandatInputDt();
        VI_gdfsuezBefCalypsoMandatV1.mandat_element mandat_element=new VI_gdfsuezBefCalypsoMandatV1.mandat_element();
        VI_gdfsuezBefCalypsoMandatV1.confirmerSignatureOuputDt confirmerSignatureOuputDt=new VI_gdfsuezBefCalypsoMandatV1.confirmerSignatureOuputDt();
        VI_gdfsuezBefCalypsoMandatV1.creerMandatOutputDt creerMandatOutputDt=new VI_gdfsuezBefCalypsoMandatV1.creerMandatOutputDt();
        VI_gdfsuezBefCalypsoMandatV1.demanderSignatureOutputDt demanderSignatureOutputDt=new VI_gdfsuezBefCalypsoMandatV1.demanderSignatureOutputDt();
        VI_gdfsuezBefCalypsoMandatV1.compteClientMajDt compteClientMajDt=new VI_gdfsuezBefCalypsoMandatV1.compteClientMajDt();
        VI_gdfsuezBefCalypsoMandatV1.lireMandatInputDt lireMandatInputDt=new VI_gdfsuezBefCalypsoMandatV1.lireMandatInputDt();
        VI_gdfsuezBefCalypsoMandatV1.donneesMandatDt donneesMandatDt=new VI_gdfsuezBefCalypsoMandatV1.donneesMandatDt();
        VI_gdfsuezBefCalypsoMandatV1.lireMandatOutputDt lireMandatOutputDt=new VI_gdfsuezBefCalypsoMandatV1.lireMandatOutputDt();
        VI_gdfsuezBefCalypsoMandatV1.composerMandatOutputDt composerMandatOutputDt=new VI_gdfsuezBefCalypsoMandatV1.composerMandatOutputDt();
        
        
        
    }
}