/*
*@Author: Amal Chreiteh
*@Description: Classe test de VI_gdfsuezComBefCalypsoPdlgaz.
*@CreatedDate: 18/03/2021
*@LastModified: 18/03/2021
*/

@isTest
public class VI_gdfsuezComBefCalypsoPdlgaz_Test {
    
    @isTest
    static void callAllMethods(){
        VI_gdfsuezComBefCalypsoPdlgaz.dernieresReleves_element dernieresReleves_element = new VI_gdfsuezComBefCalypsoPdlgaz.dernieresReleves_element();
        VI_gdfsuezComBefCalypsoPdlgaz.PDLGaz PDLGaz = new VI_gdfsuezComBefCalypsoPdlgaz.PDLGaz();
        VI_gdfsuezComBefCalypsoPdlgaz.PDLGazRoot PDLGazRoot = new VI_gdfsuezComBefCalypsoPdlgaz.PDLGazRoot();
        VI_gdfsuezComBefCalypsoPdlgaz.PITD_element PITD_element = new VI_gdfsuezComBefCalypsoPdlgaz.PITD_element();
        VI_gdfsuezComBefCalypsoPdlgaz.utilisateurFinalDt utilisateurFinalDt = new VI_gdfsuezComBefCalypsoPdlgaz.utilisateurFinalDt();
        VI_gdfsuezComBefCalypsoPdlgaz.releve6M_1MDt releve6M_1MDt = new VI_gdfsuezComBefCalypsoPdlgaz.releve6M_1MDt();
        VI_gdfsuezComBefCalypsoPdlgaz.adresseRecherchePDLGazDt adresseRecherchePDLGazDt = new VI_gdfsuezComBefCalypsoPdlgaz.adresseRecherchePDLGazDt();
        VI_gdfsuezComBefCalypsoPdlgaz.DonneesConsommationsJournalieresDt DonneesConsommationsJournalieresDt = new VI_gdfsuezComBefCalypsoPdlgaz.DonneesConsommationsJournalieresDt();
        VI_gdfsuezComBefCalypsoPdlgaz.ListePCEAdressesDt ListePCEAdressesDt = new VI_gdfsuezComBefCalypsoPdlgaz.ListePCEAdressesDt();
        VI_gdfsuezComBefCalypsoPdlgaz.installationDt installationDt = new VI_gdfsuezComBefCalypsoPdlgaz.installationDt();
        VI_gdfsuezComBefCalypsoPdlgaz.adresseRecherchePDLGazOutputDt adresseRecherchePDLGazOutputDt = new VI_gdfsuezComBefCalypsoPdlgaz.adresseRecherchePDLGazOutputDt();
        VI_gdfsuezComBefCalypsoPdlgaz.GazparDt GazparDt = new VI_gdfsuezComBefCalypsoPdlgaz.GazparDt();
        VI_gdfsuezComBefCalypsoPdlgaz.CAR_HistoDt CAR_HistoDt = new VI_gdfsuezComBefCalypsoPdlgaz.CAR_HistoDt();
        VI_gdfsuezComBefCalypsoPdlgaz.donneesCoupureDt donneesCoupureDt = new VI_gdfsuezComBefCalypsoPdlgaz.donneesCoupureDt();
        VI_gdfsuezComBefCalypsoPdlgaz.index_element index_element = new VI_gdfsuezComBefCalypsoPdlgaz.index_element();
        VI_gdfsuezComBefCalypsoPdlgaz.compteurDt compteurDt = new VI_gdfsuezComBefCalypsoPdlgaz.compteurDt();
        VI_gdfsuezComBefCalypsoPdlgaz.donneesReleveDt donneesReleveDt = new VI_gdfsuezComBefCalypsoPdlgaz.donneesReleveDt();
        VI_gdfsuezComBefCalypsoPdlgaz.derniersIndex_element derniersIndex_element = new VI_gdfsuezComBefCalypsoPdlgaz.derniersIndex_element();
        VI_gdfsuezComBefCalypsoPdlgaz.CARDt CARDt = new VI_gdfsuezComBefCalypsoPdlgaz.CARDt();
        VI_gdfsuezComBefCalypsoPdlgaz.TrancheDt TrancheDt = new VI_gdfsuezComBefCalypsoPdlgaz.TrancheDt();
        VI_gdfsuezComBefCalypsoPdlgaz.ListeCommunesDt ListeCommunesDt = new VI_gdfsuezComBefCalypsoPdlgaz.ListeCommunesDt();
        VI_gdfsuezComBefCalypsoPdlgaz.deploiement_element deploiement_element = new VI_gdfsuezComBefCalypsoPdlgaz.deploiement_element();
        VI_gdfsuezComBefCalypsoPdlgaz.CAR_element CAR_element = new VI_gdfsuezComBefCalypsoPdlgaz.CAR_element();
        VI_gdfsuezComBefCalypsoPdlgaz.donneesContractuelles_element donneesContractuelles_element = new VI_gdfsuezComBefCalypsoPdlgaz.donneesContractuelles_element();
        VI_gdfsuezComBefCalypsoPdlgaz.PDLGazAbstract PDLGazAbstract = new VI_gdfsuezComBefCalypsoPdlgaz.PDLGazAbstract();
        VI_gdfsuezComBefCalypsoPdlgaz.ConsommationJournaliereDt ConsommationJournaliereDt = new VI_gdfsuezComBefCalypsoPdlgaz.ConsommationJournaliereDt();
        VI_gdfsuezComBefCalypsoPdlgaz.adressePDLGazDt adressePDLGazDt = new VI_gdfsuezComBefCalypsoPdlgaz.adressePDLGazDt();
        
    }

}