@isTest
public class VI_gdfsuezComBefChp_Test {
    @isTest
    static void testAllMethods(){
        VI_gdfsuezComBefChpCommunV3.intervalleMontant_element test1=new VI_gdfsuezComBefChpCommunV3.intervalleMontant_element();
        VI_gdfsuezComBefChpCommunV3.refPersonneLireDt test2=new VI_gdfsuezComBefChpCommunV3.refPersonneLireDt();
        VI_gdfsuezComBefChpCommunV3.typeRemiseDt test3=new VI_gdfsuezComBefChpCommunV3.typeRemiseDt();
        VI_gdfsuezComBefChpCommunV3.monetaireDt test4=new VI_gdfsuezComBefChpCommunV3.monetaireDt();
        VI_gdfsuezComBefChpCommunV3.Dates_element test5=new VI_gdfsuezComBefChpCommunV3.Dates_element();
        VI_gdfsuezComBefChpCommunV3.PDLDt test6=new VI_gdfsuezComBefChpCommunV3.PDLDt();
        VI_gdfsuezComBefChpCommunV3.logDt test7=new VI_gdfsuezComBefChpCommunV3.logDt();
        VI_gdfsuezComBefChpCommunV3.adresseDt test8=new VI_gdfsuezComBefChpCommunV3.adresseDt();
        VI_gdfsuezComBefChpCommunV3.remiseReccurrenteDt test9=new VI_gdfsuezComBefChpCommunV3.remiseReccurrenteDt();
        VI_gdfsuezComBefChpCommunV3.intervalleDt test10=new VI_gdfsuezComBefChpCommunV3.intervalleDt();
        VI_gdfsuezComBefChpCommunV3.refPersonneMAJDt test11=new VI_gdfsuezComBefChpCommunV3.refPersonneMAJDt();
        VI_gdfsuezComBefChpCommunV3.remiseOneShotDt test12=new VI_gdfsuezComBefChpCommunV3.remiseOneShotDt();
        VI_gdfsuezComBefChpCommunV3.compteur_element test13=new VI_gdfsuezComBefChpCommunV3.compteur_element();
        VI_gdfsuezComBefChpCommunV3.horodatageDt test14=new VI_gdfsuezComBefChpCommunV3.horodatageDt();
        VI_gdfsuezComBefChpCommunV3.listeValeursDt test15=new VI_gdfsuezComBefChpCommunV3.listeValeursDt();
        VI_gdfsuezComBefChpCommunV3.contextDt test16=new VI_gdfsuezComBefChpCommunV3.contextDt();
        VI_gdfsuezComBefChpCommunV3.system_element test17=new VI_gdfsuezComBefChpCommunV3.system_element();
        VI_gdfsuezComBefChpCommunV3.canalDt test18=new VI_gdfsuezComBefChpCommunV3.canalDt();
        VI_gdfsuezComBefChpCommunV3.messageRetour_element test19=new VI_gdfsuezComBefChpCommunV3.messageRetour_element();
        
    }
}