/*
*@Author: Amal Chreiteh
*@Description: Classe test de VI_gdfsuezBefCalypsoPdlgazV3.
*@CreatedDate: 18/03/2021
*@LastModified: 18/03/2021
*/

@isTest
public class VI_gdfsuezBefCalypsoPdlgazV3_Test {
    
     @isTest
    static void callAllMethods(){
        VI_gdfsuezBefCalypsoPdlgazV3.majPDLGazResponse_element test1 = new VI_gdfsuezBefCalypsoPdlgazV3.majPDLGazResponse_element();
        VI_gdfsuezBefCalypsoPdlgazV3.creerPDLGaz_element test2 = new VI_gdfsuezBefCalypsoPdlgazV3.creerPDLGaz_element();
        VI_gdfsuezBefCalypsoPdlgazV3.creerPDLGazResponse_element test3 = new VI_gdfsuezBefCalypsoPdlgazV3.creerPDLGazResponse_element();
        VI_gdfsuezBefCalypsoPdlgazV3.majPDLGaz_element test4 = new VI_gdfsuezBefCalypsoPdlgazV3.majPDLGaz_element();
        VI_gdfsuezBefCalypsoPdlgazV3.majPDLGazInputDt test5 = new VI_gdfsuezBefCalypsoPdlgazV3.majPDLGazInputDt();
        VI_gdfsuezBefCalypsoPdlgazV3.rechercherPDLGaz_element test6 = new VI_gdfsuezBefCalypsoPdlgazV3.rechercherPDLGaz_element();
        VI_gdfsuezBefCalypsoPdlgazV3.rechercherPDLGazInputDt test7 = new VI_gdfsuezBefCalypsoPdlgazV3.rechercherPDLGazInputDt();
        VI_gdfsuezBefCalypsoPdlgazV3.PDLGaz_element test8 = new VI_gdfsuezBefCalypsoPdlgazV3.PDLGaz_element();
        VI_gdfsuezBefCalypsoPdlgazV3.lirePDLGazInputDt test9 = new VI_gdfsuezBefCalypsoPdlgazV3.lirePDLGazInputDt();
        VI_gdfsuezBefCalypsoPdlgazV3.rechercherPDLGazResponse_element test10 = new VI_gdfsuezBefCalypsoPdlgazV3.rechercherPDLGazResponse_element();
        VI_gdfsuezBefCalypsoPdlgazV3.lirePDLGazOutputDt test11 = new VI_gdfsuezBefCalypsoPdlgazV3.lirePDLGazOutputDt();
        VI_gdfsuezBefCalypsoPdlgazV3.rechercherPDLGazOutputDt test12 = new VI_gdfsuezBefCalypsoPdlgazV3.rechercherPDLGazOutputDt();
        VI_gdfsuezBefCalypsoPdlgazV3.lirePDLGazResponse_element test13 = new VI_gdfsuezBefCalypsoPdlgazV3.lirePDLGazResponse_element();
        VI_gdfsuezBefCalypsoPdlgazV3.majPDLGazOutputDt test14 = new VI_gdfsuezBefCalypsoPdlgazV3.majPDLGazOutputDt();
        VI_gdfsuezBefCalypsoPdlgazV3.lirePDLGaz_element test15 = new VI_gdfsuezBefCalypsoPdlgazV3.lirePDLGaz_element();
        VI_gdfsuezBefCalypsoPdlgazV3.creerPDLGazOutputDt test16 = new VI_gdfsuezBefCalypsoPdlgazV3.creerPDLGazOutputDt();
        VI_gdfsuezBefCalypsoPdlgazV3.Dependency test17 = new VI_gdfsuezBefCalypsoPdlgazV3.Dependency();
         VI_gdfsuezBefCalypsoPdlgazV3.creerPDLGazInputDt test18 = new VI_gdfsuezBefCalypsoPdlgazV3.creerPDLGazInputDt();
       
        
    }

}