/*
*@Auhtor: Paul Ghoussoub
*@Description: Classe de test de VI_gdfsuezComBefChpPivotRelanceMandat
*@CreatedDate: 26/03/2021
*/
@isTest
public class VI_gdfsuezComBefChpPivotRelance_Test {
    @istest
    static void testMethod1(){
        VI_gdfsuezComBefChpPivotRelanceMandat.system_element element=new VI_gdfsuezComBefChpPivotRelanceMandat.system_element();
        VI_gdfsuezComBefChpPivotRelanceMandat.systemPath_element systemPath_element=new VI_gdfsuezComBefChpPivotRelanceMandat.systemPath_element();
        VI_gdfsuezComBefChpPivotRelanceMandat.messageRetour_element messageRetour_element=new VI_gdfsuezComBefChpPivotRelanceMandat.messageRetour_element();
        VI_gdfsuezComBefChpPivotRelanceMandat.refPersonneCreerDt refPersonneCreerDt=new VI_gdfsuezComBefChpPivotRelanceMandat.refPersonneCreerDt();
        VI_gdfsuezComBefChpPivotRelanceMandat.listeValeursParticulieresDt listeValeursParticulieresDt=new VI_gdfsuezComBefChpPivotRelanceMandat.listeValeursParticulieresDt();
        VI_gdfsuezComBefChpPivotRelanceMandat.refPersonneMAJDt refPersonneMAJDt=new VI_gdfsuezComBefChpPivotRelanceMandat.refPersonneMAJDt();
        VI_gdfsuezComBefChpPivotRelanceMandat.refPersonneLireDt refPersonneLireDt=new VI_gdfsuezComBefChpPivotRelanceMandat.refPersonneLireDt();
        VI_gdfsuezComBefChpPivotRelanceMandat.listeValeursDt listeValeursDt=new VI_gdfsuezComBefChpPivotRelanceMandat.listeValeursDt();
        VI_gdfsuezComBefChpPivotRelanceMandat.messageRetoursDt messageRetoursDt=new VI_gdfsuezComBefChpPivotRelanceMandat.messageRetoursDt();
        VI_gdfsuezComBefChpPivotRelanceMandat.contextDt contextDt=new VI_gdfsuezComBefChpPivotRelanceMandat.contextDt();
    }
}