/*
*@Author: Eloi Dereeper
*@Description: Class test pour VI_UTIL006_Cache_Management
*@CreatedDate: 27/11/2020
*@LastModified: 27/11/2020
*/
@isTest
public class VI_UTIL006_Cache_Management_Test {
    
    @isTest
    public static void test_getIdentifiantDistribFromApex(){
        VI_UTIL006_Cache_Management VI_Cache = new VI_UTIL006_Cache_Management();
        VI_Cache.getIdentifiantDistribFromApex();
    }
    
}