export default function getFakeElecData() {
    return [
        {
            categorie: "--",
            consommationCadran: "271",
            dateDebut: "16/04/21",
            dateFin: "16/05/21",
            dateReleve: "16/05/21",
            idFacture: "--",
            indexDebut: "854",
            indexFin: "884",
            originReleve: "Fournisseur",
            raison: "Relève normale",
            typeComptage: "--",
            typeCompteur: "Classique",
            typeReleve: "--",
            kwh: "300"
        },
        {
            categorie: "--",
            consommationCadran: "301",
            dateDebut: "16/05/21",
            dateFin: "16/06/21",
            dateReleve: "16/06/21",
            idFacture: "--",
            indexDebut: "884",
            indexFin: "914",
            originReleve: "Fournisseur",
            raison: "Relève normale",
            typeComptage: "--",
            typeCompteur: "Classique",
            typeReleve: "--",
            kwh: "300"
        },
        {
            categorie: "--",
            consommationCadran: "331",
            dateDebut: "16/06/21",
            dateFin: "16/07/21",
            dateReleve: "16/07/21",
            idFacture: "--",
            indexDebut: "914",
            indexFin: "944",
            originReleve: "Fournisseur",
            raison: "Relève normale",
            typeComptage: "--",
            typeCompteur: "Classique",
            typeReleve: "--",
            kwh: "300"
        },
        {
            categorie: "--",
            consommationCadran: "361",
            dateDebut: "16/07/21",
            dateFin: "16/08/21",
            dateReleve: "16/08/21",
            idFacture: "--",
            indexDebut: "944",
            indexFin: "974",
            originReleve: "Fournisseur",
            raison: "Relève normale",
            typeComptage: "--",
            typeCompteur: "Classique",
            typeReleve: "--",
            kwh: "300"
        },
        {
            categorie: "--",
            consommationCadran: "391",
            dateDebut: "16/08/21",
            dateFin: "16/09/21",
            dateReleve: "16/09/21",
            idFacture: "--",
            indexDebut: "974",
            indexFin: "1004",
            originReleve: "Fournisseur",
            raison: "Relève normale",
            typeComptage: "--",
            typeCompteur: "Classique",
            typeReleve: "--",
            kwh: "300"
        },
        {
            categorie: "--",
            consommationCadran: "421",
            dateDebut: "16/09/21",
            dateFin: "16/10/21",
            dateReleve: "16/10/21",
            idFacture: "--",
            indexDebut: "1004",
            indexFin: "1034",
            originReleve: "Fournisseur",
            raison: "Relève normale",
            typeComptage: "--",
            typeCompteur: "Classique",
            typeReleve: "--",
            kwh: "300"
        },
        {
            categorie: "--",
            consommationCadran: "451",
            dateDebut: "16/10/21",
            dateFin: "16/11/21",
            dateReleve: "16/11/21",
            idFacture: "--",
            indexDebut: "1034",
            indexFin: "1064",
            originReleve: "Fournisseur",
            raison: "Relève normale",
            typeComptage: "--",
            typeCompteur: "Classique",
            typeReleve: "--",
            kwh: "300"
        },
        {
            categorie: "--",
            consommationCadran: "481",
            dateDebut: "16/11/21",
            dateFin: "16/12/21",
            dateReleve: "16/12/21",
            idFacture: "--",
            indexDebut: "1064",
            indexFin: "1094",
            originReleve: "Fournisseur",
            raison: "Relève normale",
            typeComptage: "--",
            typeCompteur: "Classique",
            typeReleve: "--",
            kwh: "300"
        },
        {
            categorie: "--",
            consommationCadran: "501",
            dateDebut: "16/12/21",
            dateFin: "16/01/22",
            dateReleve: "16/01/22",
            idFacture: "--",
            indexDebut: "1094",
            indexFin: "1124",
            originReleve: "Fournisseur",
            raison: "Relève normale",
            typeComptage: "--",
            typeCompteur: "Classique",
            typeReleve: "--",
            kwh: "300"
        },
        {
            categorie: "--",
            consommationCadran: "531",
            dateDebut: "16/01/22",
            dateFin: "16/02/22",
            dateReleve: "16/02/22",
            idFacture: "--",
            indexDebut: "1124",
            indexFin: "1154",
            originReleve: "Fournisseur",
            raison: "Relève normale",
            typeComptage: "--",
            typeCompteur: "Classique",
            typeReleve: "--",
            kwh: "300"
        },
        {
            categorie: "--",
            consommationCadran: "561",
            dateDebut: "16/02/22",
            dateFin: "16/03/22",
            dateReleve: "16/03/22",
            idFacture: "--",
            indexDebut: "1154",
            indexFin: "1184",
            originReleve: "Fournisseur",
            raison: "Relève normale",
            typeComptage: "--",
            typeCompteur: "Classique",
            typeReleve: "--",
            kwh: "300"
        },
        {
            categorie: "--",
            consommationCadran: "561",
            dateDebut: "16/03/22",
            dateFin: "16/04/22",
            dateReleve: "16/04/22",
            idFacture: "--",
            indexDebut: "1154",
            indexFin: "1184",
            originReleve: "Fournisseur",
            raison: "Relève normale",
            typeComptage: "--",
            typeCompteur: "Classique",
            typeReleve: "--",
            kwh: "300"
        }
    ];
}